# Generated by Django 2.2.17 on 2021-02-21 17:43

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('estadodelmce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communistparty',
            name='trend',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('item_key1', 'Item title 1.1'), ('item_key2', 'Item title 1.2'), ('item_key3', 'Item title 1.3'), ('item_key4', 'Item title 1.4'), ('item_key5', 'Item title 1.5')], default='hola', max_length=49),
        ),
    ]
