# Generated by Django 2.2.17 on 2021-02-22 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estadodelmce', '0004_auto_20210221_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communistparty',
            name='trend',
        ),
    ]
