# Generated by Django 2.2.17 on 2021-02-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadodelmce', '0003_auto_20210221_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communistparty',
            name='acronym',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
